name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.2.0
  - seaborn=0.11.1
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - pandas-profiling=2.6.0
  - pyarrow=2.0
  - jinja2<3.1.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0



